name: Update Packagist

on:
  push:
    tags:
      - '*'
  release:
    types: [published]

jobs:
  packagist:
    runs-on: ubuntu-latest
    steps:
      - name: Update Packagist
        run: |
          curl -s -XPOST \
            -H 'Content-Type: application/json' \
            "https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_TOKEN }}" \
            -d '{"repository":{"url":"https://github.com/upgradelabs/sentinel-laravel"}}'
